server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /mers-ping {
    proxy_pass http://107.102.8.148/MERS/cekorder.php?ping=1;
    proxy_method HEAD;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_connect_timeout 3s;
    proxy_read_timeout 3s;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
